services:
  strapi:
    container_name: strapi
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi_net

networks:
  strapi_net:
    name: strapi_net
